# MongoDB connection
quarkus.mongodb.connection-string=mongodb://${DB_REMOTE_HOST}
quarkus.mongodb.database=cpaas_currency

# Liquibase MongoDB
quarkus.liquibase-mongodb.migrate-at-start=true
quarkus.liquibase-mongodb.change-log=db/db-changelog-root.xml
